### PR TITLE
Support for --all command to include entire team

### LINKED ISSUE #28: --all flag to add everybody
Sometimes you need to add the entire team to a commit message (mob programming).

GCommit would benefit from a `--all` flag that does the job. A bonus would be `-a` alias.

### PR DESCRIPTION
**Pull request by ParthPratim**
Signed-off-by: Parth Pratim Chatterjee <parth27official@gmail.com>

## Proposed Changes

# Support for --all command
Adds support for --all command to include entire team into commit sign off list.
Usage :
```plain
git gcommit --all
```
## Issue

Closes/Fixes #28

### CODE REVIEW

**Comment by jooaodanieel** [comment]
Hi @ParthPratim would you mind to also change the README to include instructions about this usage and also to include yourself into the list of contributors?

**Comment by ParthPratim** [comment]
I have made the changes as suggested by you. Do let me know if I should do anything else too.

Thank You.

**Comment by jooaodanieel** [comment]
Would you mind to resolve these conflicts, @ParthPratim ? I just merged the other PR

**Comment by ParthPratim** [comment]
I've just resolved the conflicts. Thanks.

**Pull request merged**
