### PR TITLE
[prevent committing when no changes] 

### PR DESCRIPTION
**Pull request by doriancodes**
## Proposed Changes

* added retrieveStatus method, to check if there are any changes to commit
* modified the run method to check for the status of the work tree
*if there are no changes to commit a GCommitException with a meaningful message is thrown

## Issue

Closes/Fixes : https://github.com/jooaodanieel/GCommit/issues/56

### CODE REVIEW

**Comment by jooaodanieel** [comment]
Hi @doriancodes thanks for your contribution!

I checked out your fork to test, and I found your implementation still has the issue.

In the case there are no changes in the repo, your implementation captures that correctly 🚀 

The issue is when there are changes, but they haven't been added to staging. In such case, GCommit should not accept the commit (it should throw the exception as well), but your implementation is allowing the commit.

---

The steps to reproduce what I did here:
1. I built the latest .kexe based on your fork and branch
2. I changed README.md file
3. I ran `git status --porcelain`, which gave me `M README.md`
3. I ran the new .kexe and it opened the commit message

**Comment by jooaodanieel** [comment]
Ah, @doriancodes a little something it's missing: your name and pic in the README table of contributors! You only added the reference as a markdown link

**Comment by doriancodes** [comment]
You're right! I've overseen that before! Now with the new changes it should be able to pick unstaged changes as well :) I've also added my picture :)

**Comment by jooaodanieel** [comment]
That works! Thanks once again @doriancodes 
Happy Hacktoberfest 👨🏼‍💻 🚀

**Pull request merged**
