### PR TITLE
GCommit to Git Wrapper

### LINKED ISSUE #2: Turn GCommit into a commit wrapper
`git gcommit` is not a `git commit` wrapper, but it would be nice to have it as a full wrapper that only adds the team-signature behavior.

Suggestion: use a new flag that accept a list to differentiate from default `git commit` behavior, for example, add a `git commit --team [ID1 ...]`

### PR DESCRIPTION
**Pull request by ParthPratim**
Signed-off-by: Parth Pratim Chatterjee <parth27official@gmail.com>

## Proposed Changes
This allows you to call native ```git commit``` command line options from ``` git gcommit``` Format :
```plain
git gcommit [INITIALS...] [git command line options .....]
```
Sample Usage : 
```plain
git gcommit JB MB --amend
```

## Issue

Closes/Fixes #2

### CODE REVIEW

**Comment by jooaodanieel** [comment]
@ParthPratim I'm concerned with the `--all` flag, that is ambiguous (both `commit` and `gcommit` accept the same flag)
Can you do something related?

**Comment by ParthPratim** [comment]
Yeah you're right. But I thing finding a work around for this problem would be something like a hack which is very risky to ship.
 
What I can suggest is we can rename the ```--all``` flag of ```gcommit``` to ```--inc-all``` (include-all)  which makes it more intuitive.
Can we do this ?

**Comment by jooaodanieel** [comment]
Oh this gave me an idea to keep semantics
We could use `--sign-all` to reference the Signed-off-by! What do you say?

**Comment by ParthPratim** [comment]
I thing ```--sign-all``` sounds great !
I'll make the changes.
Thanks.

**Comment by jooaodanieel** [comment]
@ParthPratim I'm facing an error when I try the following

```
mkdir /path/to/test && cd /path/to/test

git init

echo 'JD="Joao Daniel <jotaf.daniel@gmail.com>"' > .gitteam

echo "foo" > foo.txt
echo "baz" > baz.txt

git gcommit --all --sign-all
```

The error:
```
Traceback (most recent call last):
  File "/usr/src/local/bin/git-gcommit", line 168, in <module>
    main()
  File "/usr/src/local/bin/git-gcommit", line 146, in main
    if(args.exceptcomm):
AttributeError: 'tuple' object has no attribute 'exceptcomm'
```
Would you like me to open an issue with this problem to open for other people and give you a break? I'm worried whether this is getting boring to you

**Comment by ParthPratim** [comment]
I just fixed it. It was using the wrong variable. 

The ```all_args``` variable is a Tuple where the 0th index consists of the arguments which is known to gcommit  (```gc_args``` ) and the 1st index arguments are the ones which are passed on to ```git commit``` that is ```c_args```.

**Comment by jooaodanieel** [comment]
Perfect, @ParthPratim !

**Pull request merged**
